language: go

go:
  - 1.7
  - 1.8
  - master

go_import_path: github.com/OSSystems/hulk

matrix:
  allow_failures:
    - go: master

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - libarchive-dev
      - glide

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - glide install
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls

install: true

env:
  secure: "eHUUa5WWhyvuAkljzCFYKZhyH0RwMSX2Mew5z9EDupc5zCGNlvbKR6VF9iTtKUpEqUO1sQJybkf2nz1FZgJySQI95Jr4cJEfioSoR+9Y8J2ueBtpsCd3Z0Y66t+csLtBzJIjk69K6qJ2fND8rJjNieqN8WNYMx4y9LT0eF/ZiQoqkPZaQ0FYDviMPFUXCHbpxoD+lrAiOWYwDsj3i/fTTsfUt67W5JHy03nv1bFifT6YbLeP8KYfSyaLTctl7s1gQhXHqMk/2F4Q69q0f1RITAOI+iBLzX0OLcOHPc3RNkwLG2G2J0QBA61ZQThrMi7hdGOvg+tagV2w1qfHgfB/CLbL+qP20+DvfN0g7E0VeXXwGCFzmpWdgJGOJ5aHhnzaavyQnRF638fT+5AFBvpGY7jbwqlvvjQB680SuZUl0gA0ktV16NbiFHuzOasRsYL6peem/NseuxuiKVrmBzJ6qYlKI/7prNQiby/b/tmJXmmHGgKuy0qvReXJMZ6MFeKv8+jUkFTfcK9wygrHABuLDm8BI+JlRkrp6EYzI6rUfVN9g2CKer3/CdZdR6I/0mXT1wB4A2zimz1HJHP3oFo87PcR77eOnfIkASAlLZIR1riAs4sYy3QSVsQ4rfiyi71hma/TI7EMkp9lzFRkm5+Z4HpFV7G6kEp9FmQr64LwmIY="

script:
  - gometalinter --deadline=30s --aggregate || true
  - go test -race $(glide novendor)
  - overalls -project=github.com/OSSystems/hulk -covermode=count -ignore=.git,vendor -debug

after_success:
  - goveralls -coverprofile=overalls.coverprofile -ignore main.go
